### ISSUE TITLE
Your openAI secret key is published

### ISSUE THREAD

**Issue by oelmekki** [yding25/GPT-Planner#1]
Hi,

Just a fair warning that you've published your API key:

https://github.com/yding25/GPT-Planner/blob/2fa2a872c19738b78c61731e33dc6430dc2d3df7/dataset/backup/openai_api_key.txt#L1

 If you have a a paying account on openAI's api and this key is still valid, it may be used to access the api while billing you. You should probably deactivate this key in openAI's dashboard and remove it from your code, using instead an environment variable or similar.

**Comment by COWPlanning** [comment]
Thanks for the reminder. The API was revoked.

**Comment by yding25** [comment]
Thanks for the reminder. The API was revoked.
