### ISSUE TITLE
Robot physical verification

### ISSUE THREAD

**Issue by 3202336152** [yding25/GPT-Planner#3]
Thank you for your excellent work!
I would like to ask if the code only gives task planning code? Didn't you give the code for the accuracy verification and robot physical experiment in the paper?

**Comment by yding25** [comment]
Hi, thank you for your question. We involve human evaluators in the assessment of the generated outcomes, which is not an automated process. The methodology for evaluating the results through human intervention is detailed in the experimental settings section of the paper.
