### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fenjenahwe** [yding25/GPT-Planner#4]
Hello, thank you for sharing this impressive work.
I noticed that there is no explicit license* included in your code and I would like to ask if you would consider adding one?
I am currently a master student and am interested in building some additions to your framework for my final project - would that be permissible?
Thanks.

*https://choosealicense.com/

**Comment by yding25** [comment]
Hi,

Thank you for your interest in my project. I have updated the license.
Please feel free to reach out if you have any questions or require
assistance—I'm more than happy to help in any way I can.


Best,
Yan Ding
